import "./globals.css";
import PageAnimation from "../components/PageAnimation";
import Providers from "@/components/Providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr" className="htmltest">
			<body className="font-montreal text-default bg-bgcolor">
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
}
