import "./globals.css";
import PageAnimation from "../components/PageAnimation";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body className="font-montreal text-text-primary bg-background">
				<PageAnimation>{children}</PageAnimation>
			</body>
		</html>
	);
}
